// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MielMasse.Data;

#nullable disable

namespace MielMasse.Migrations
{
    [DbContext(typeof(MielMasseDbContext))]
    partial class MielMasseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MielMasse.Models.Domain.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gsm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbFilleuls")
                        .HasColumnType("int");

                    b.Property<int>("NbFilleulsUsed")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParrainNom")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Preferences")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParrainNom");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("MielMasse.Models.Domain.Utilisateur", b =>
                {
                    b.HasOne("MielMasse.Models.Domain.Utilisateur", "Parrain")
                        .WithMany()
                        .HasForeignKey("ParrainNom");

                    b.Navigation("Parrain");
                });
#pragma warning restore 612, 618
        }
    }
}
